### ISSUE TITLE
What license is this code released under and is there a CLA for code contributions?

### ISSUE THREAD

**Issue by gerrith3** [ericsink/cb#11]
Our legal is asking what license this code is released under and we don't see anything to inform us on that.  Is it possible to associate a license with this project via the README, a CONTIRBUTING file or even a github license label?

**Comment by ericsink** [comment]
I've added a LICENSE file and updated the README to mention it.

There is no CLA for code contributions.

**Comment by gerrith3** [comment]
Excellent - thank you very much!
