### ISSUE TITLE
Add support for wasm

### ISSUE THREAD

**Issue by bricelam** [ericsink/cb#4]
The .NET tooling for web assembly is coming together, and soon the masses will demand SQLite in their browsers!

I know @jeromelaban did a bunch of work in [unoplatform/Uno.sqlite-wasm](https://github.com/unoplatform/Uno.sqlite-wasm) to produce an `e_sqlite3.bc` file. What would it take to make this an official part of the main `SQLitePCLRaw.provider.e_sqlite3` package?

IIRC, we're also waiting on the .NET team (mono-wasm team?) to define how *.bc files should be packaged so they flow through the toolchain into Emscripten. (I vaguly remember Immo mentioning something like a `browser-wasm` RID at one point.) Once this happens, I presume the same package could then work for both Blazor and Uno projects.

/cc @danroth27 @JeremyLikness @lewing @radical

**Comment by ericsink** [comment]
Whoa.

I'll just say for now that all my wasm knowledge is (1) outdated, and (2) focused on WASI (aka wasm *outside* the browser).

So I will enter this discussion with a desire to be helpful and cooperative, but without much clue.

**Comment by bricelam** [comment]
lol, +1. I barely know what I'm talking about.

@jeromelaban Do you know if the SQLite amalgamation required any patching to get it to compile? If so, do you know if the SQLite team eventually intends to maintain compatibility with emcc?

**Comment by jeromelaban** [comment]
@bricelam the [wasm build](https://github.com/unoplatform/Uno.sqlite-wasm/blob/master/Makefile) I'm creating is done from the untouched amalgamation . There's a specific [config file](https://github.com/unoplatform/Uno.sqlite-wasm/blob/master/src/c/config.h), though.

I don't know if the sqlite team intends to support webassembly, and until emscripten gets a stable ABI, it's going to need multi-emscripten version support using [something like this](https://github.com/unoplatform/Uno.Wasm.Bootstrap#static-linking-multi-version-support).

Also note that the support for .NET 5/6 for sqlitepcl.raw needs https://github.com/ericsink/SQLitePCL.raw/issues/423 to work properly.

**Comment by lewing** [comment]
> I don't know if the sqlite team intends to support webassembly, and until emscripten gets a stable ABI, it's going to need multi-emscripten version support using [something like this](https://github.com/unoplatform/Uno.Wasm.Bootstrap#static-linking-multi-version-support).
> 

for net6 there is a reasonable chance we will pin an emscripten version so targeting net6.0 wouldn't require that sort of multiversioning

**Comment by jeromelaban** [comment]
> for net6 there is a reasonable chance we will pin an emscripten version so targeting net6.0 wouldn't require that sort of multiversioning

This would make nuget packages tied to a specific runtime version, without any possible backward/forward compatibility unless the target framework is bumped as well. It'll work for about a year in the ecosystem, while being particularly annoying those testing out .NET 7 previews as they'll have to troubleshoot weird native linker issues...

Having to build multiple versions of emscripten requires a bit more work on both runtime and library ends, but it makes libraries a bit more able to be future and backward compatible without relying on preview versions of the runtime.

**Comment by filipnavara** [comment]
I'm trying to automate the annoying parts of the build (https://github.com/ericsink/cb/pull/5). At the moment I started with replicating the existing targets but I do plan to add support for some missing Apple Silicon targets later. I suspect adding WASM builds would be slightly painful but once it's done it should make the maintenance reasonable. Depending on whether emscripten version is fixed or not we may need some dependabot/arcade magic to auto-update. I am not too familiar with that unfortunately.

**Comment by danroth27** [comment]
@stevesandersonms

**Comment by danroth27** [comment]
:rocket:
